### ISSUE TITLE
Sync delete operations before inserts and updates

### ISSUE THREAD

**Issue by rywall** [culturecode/stagehand#48]
Otherwise we can run into problems with unique index violations. For example, if you delete a record and then add another one with the same value in a unique index column.

See https://github.com/combinaut/sparkle-scripps/issues/523

**Comment by njakobsen** [comment]
Ah, looks like we do it here https://github.com/culturecode/stagehand/blob/173ac1312448f1d6f23787063895f13669e38267/lib/stagehand/staging/synchronizer.rb#L90, but not when we go via checklist syncing.

**Comment by rywall** [comment]
I don't see it being done there? That is just ID desc. We sometimes need to do earlier IDs first if they are delete operations.
